// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ApolloContext from "../lib/ApolloContext.js";
import Header from '../components/Header';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="px-7">
        <ApolloContext>
          <Header />
          {children}
        </ApolloContext>
      </body>
    </html>
  );
}
